### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by the-codingninja** [0x48piraj/fossbot#1]
- [x] I'm new to FOSSASIA ... or First time user -  I see you are new, toast ... best practices .. Projects link ..
- [x] Thanks @fossbot - No problem, I am a bot made just made for you and our community
- [x] "who created you" 
- [x] fossbot suggest <language> - @mention replies with link to project of specific language :rocket: 

*.... Anything you feel is missing you can add here*

**Comment by 0x48piraj** [comment]
- [x] **Welcome Script** :wink:

**Comment by 0x48piraj** [comment]
- [x] **Thanks @fossbot**

**Comment by 0x48piraj** [comment]
- [x] Creators :+1:

**Comment by 0x48piraj** [comment]
Suggest :heart: :+1:

**Comment by 0x48piraj** [comment]
### Closing this **TODO**!

_Job Completed!_  :100:
